# Generated by Django 5.1.7 on 2025-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "make_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.make"
                    ),
                ),
            ],
            options={
                "ordering": ["make_id__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="MotorHome",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("year", models.IntegerField()),
                ("mileage", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("color", models.CharField(max_length=100)),
                (
                    "ticket_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("is_new", models.BooleanField(default=True)),
                ("for_sale", models.BooleanField(default=True)),
                ("for_service", models.BooleanField(default=False)),
                ("for_rental", models.BooleanField(default=False)),
                ("is_sold", models.BooleanField(default=False)),
                ("sold_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.model",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
    ]
