# Generated by Django 5.1.7 on 2025-03-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_model_modelvehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorhome",
            name="price",
        ),
        migrations.AddField(
            model_name="motorhome",
            name="condition",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="motorhome",
            name="mileage",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="motorhome",
            name="ticket_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="motorhome",
            name="sold_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
