# Generated by Django 5.1.7 on 2025-03-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_rename_make_modelvehicle_make_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModelVehicle",
            new_name="Model",
        ),
    ]
