# Generated by Django 5.1.7 on 2025-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_modelvehicle_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorhome",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
