# Generated by Django 5.1.7 on 2025-03-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_motorhome_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorhome",
            name="for_rental",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="motorhome",
            name="for_service",
            field=models.BooleanField(default=False),
        ),
    ]
