# Generated by Django 5.1.7 on 2025-03-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_motorhome_for_rental_motorhome_for_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['make_id__name', 'name']},
        ),
    ]
