# Generated by Django 5.1.7 on 2025-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_model_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorhome",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
