# Generated by Django 5.1.7 on 2025-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_motorhome_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorhome",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
