# Generated by Django 5.1.7 on 2025-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePerson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceTicket",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("service_start_date", models.DateField()),
                (
                    "service_end_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "service_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_warranty", models.BooleanField(default=False)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "motor_home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.motorhome",
                    ),
                ),
                (
                    "service_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.serviceperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item_description", models.TextField(blank=True, null=True)),
                (
                    "item_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service.serviceticket",
                    ),
                ),
            ],
        ),
    ]
