# Generated by Django 5.1.7 on 2025-03-26 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceticket",
            old_name="service_date",
            new_name="service_end_date",
        ),
        migrations.AddField(
            model_name="serviceticket",
            name="service_start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
