# Generated by Django 5.1.7 on 2025-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_rename_service_date_serviceticket_service_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceticket",
            name="service_end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
