# Generated by Django 5.1.7 on 2025-03-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_serviceticket_service_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceticket",
            name="service_description",
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item_description", models.TextField()),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "service_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service.serviceticket",
                    ),
                ),
            ],
        ),
    ]
