# Generated by Django 5.1.7 on 2025-03-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_serviceticket_service_description_serviceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceticket",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="item_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="serviceticket",
            name="service_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
