# Generated by Django 5.1.7 on 2025-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
