# Generated by Django 5.1.7 on 2025-03-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPerson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sale_date", models.DateField()),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("on_hold", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "warranty_end_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "motor_home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.motorhome",
                    ),
                ),
                (
                    "sales_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.salesperson",
                    ),
                ),
            ],
        ),
    ]
